name: Get defaults on CI

on:
  workflow_dispatch:
    inputs:
      full:
        type: boolean
        description: Do a slower full run (5 minutes)?
        default: false

jobs:
  build-defaults:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: 
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
          # TODO: whenever the available runners change, these need to be updated
          - "ubuntu-20.04"
          - "windows-2019"
          - "macos-11"
          - "macos-13"
        do-full:
          - ${{ inputs.full }}
        exclude:
          - do-full: false
            os: macos-latest
            python-version: "3.9"
          - do-full: false
            os: macos-11
            python-version: "3.9"
          - do-full: false
            os: macos-13
            python-version: "3.9"
          - do-full: false
            os: macos-latest
            python-version: "3.10"
          - do-full: false
            os: macos-11
            python-version: "3.10"
          - do-full: false
            os: macos-13
            python-version: "3.10"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      if: ${{ !(startswith(matrix.os, 'macos-') && contains('3.8;3.9;3.10', matrix.python-version)) }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: (Ubuntu) Install Xvfb
      shell: bash
      if: ${{ startswith(matrix.os, 'ubuntu-') }}
      run: sudo apt-get install -y xvfb
    - name: (MacOS, <3.11) Install pyenv
      shell: bash
      if: ${{ startswith(matrix.os, 'macos-') && contains('3.8;3.9;3.10', matrix.python-version) }}
      run: |
        export HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK=1
        PY_PKG="python-tk@${{ matrix.python-version }}"
        PY_PKG_PY="python@${{ matrix.python-version }}"
        brew install --overwrite $PY_PKG_PY $PY_PKG
        brew link --overwrite $PY_PKG_PY $PY_PKG
        echo "[DEBUG] Installed python from brew"
        echo "Running on $(python --version)"
        echo "Located at $(whereis python)"
        echo "With PATH = $PATH"
        PY_PATH=$(brew --prefix $PY_PKG)
        PY_PATH_PY="$(brew --prefix $PY_PKG_PY)/libexec/bin"
        echo "$PY_PATH" >> "$GITHUB_PATH"
        echo "$PY_PATH_PY" >> "$GITHUB_PATH"
        export PATH="$PY_PATH:$PY_PATH_PY:$PATH"
        echo "[DEBUG] Updated path"
        echo "Running on $(python --version)"
        echo "Located at $(whereis python)"
        echo "With PATH = $PATH"
        PYVER_S=$(python --version)
        if [[ ! $PYVER_S =~ "Python ${{ matrix.python-version }}." ]] ; then
          echo "[ERROR] Using wrong python version"
          exit 1
        fi
    - name: (MacOS, <3.11) Install python with working tkinter
      shell: bash
      if: ${{ startswith(matrix.os, 'macos-') && contains('3.8;3.9;3.10', matrix.python-version) }}
      run: |
        whereis python
        whereis python3
        echo $PATH
        python --version
    - name: Run python script (with fallbacks)
      id: run_main
      shell: bash {0}
      run: |
        echo "Running on $(python --version)"
        echo "Located at $(whereis python)"
        echo "With PATH = $PATH"
        EXIT_XVFB=9
        EXIT_FALLBACK=9
        echo "Running normally"
        python -m write_curr_defaults
        EXIT_NORMAL=$?
        if [ "$EXIT_NORMAL" -ne "0" ] ; then
          echo "Trying to start Xvfb"
          type Xvfb
          Xvfb :0 -screen 0 1024x768x16 &
          EXITSTATUS_XVFB=$?
          if [ "$EXITSTATUS_XVFB" -ne "0" ] ; then
            echo "Couldn't run Xvfb"
            EXIT_XVFB="$EXITSTATUS_XVFB"
          else
            sleep 2
            ps aux | grep Xvfb
            echo "Running under Xvfb"
            DISPLAY=:0.0 python -m write_curr_defaults
            EXIT_XVFB=$?
          fi
          if [ "$EXIT_XVFB" -ne "0" ] ; then
            echo "Running fallback"
            TK_DEFAULTS_FALLBACK=1 python -m write_curr_defaults
            EXIT_FALLBACK=$?
          fi
        fi
        if [ "$EXIT_NORMAL" -eq "0" ] || [ "$EXIT_XVFB" -eq "0" ] || [ "$EXIT_FALLBACK" -eq "0" ] ; then
          FILENAME=$(cat ./curr_out_filename.txt)
          if [ -z "$FILENAME" ] ; then
            echo "Error: curr_out_filename not set"
            exit 1
          fi
          echo "outfile_name=$FILENAME"
          echo "outfile_name=$FILENAME" >> "GITHUB_OUTPUT"
          exit 0
        else
          exit 1
        fi
    - name: Upload artifact for the defaults
      uses: actions/upload-artifact@v4
      with:
        name: "_out_tkinter_defaults__${{ matrix.os }}_${{ matrix.python-version }}"
        path: "tkinter_defaults_curr.json"
    - name: Upload artifact for merge step
      uses: actions/upload-artifact@v4
      with:
        name: zz_for_merge__${{ matrix.python-version }}_${{ matrix.os}}
        path: |
          tkinter_defaults_curr.json
          curr_out_filename.txt
  # Collect and commit results from the other runs
  commit-results:
    needs:
      - "build-defaults"
    permissions:
      contents: write
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: "./downloaded_artifacts"
          pattern: "zz_for_merge__*"
      - name: Write downloaded artifacts to tkinter_defaults
        run: python -m write_downloaded_artifacts
      - name: Merge defaults
        run: python -m merge_defaults
      - name: Check written files
        run: |
          ls tkinter_defaults
          ls merged_defaults
      - name: Upload defaults
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Upload defaults [bot]
          commit_author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          file_pattern: "merged_defaults/*.json tkinter_defaults/*.json"
