name: Get defaults on CI

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        os: 
          - "ubuntu-latest"
          - "windows-latest"
          - "macos-latest"
          # TODO: whenever the available runners change, these need to be updated
          - "ubuntu-20.04"
          - "windows-2019"
          - "macos-11"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: (Ubuntu) Install Xvfb
      shell: bash
      if: ${{ startswith(matrix.os, 'ubuntu-') }}
      run: sudo apt-get install -y xvfb
    - name: (MacOS, <3.11) Fix Python's tkinter
      shell: bash
      if: ${{ startswith(matrix.os, 'macos-') && includes(['3.9', '3.10'], matrix.python-version) }}
      run: |
        brew install tcl-tk pyenv
        env \
          PATH="$(brew --prefix tcl-tk)/bin:$PATH" \
          LDFLAGS="-L$(brew --prefix tcl-tk)/lib" \
          CPPFLAGS="-I$(brew --prefix tcl-tk)/include" \
          PKG_CONFIG_PATH="$(brew --prefix tcl-tk)/lib/pkgconfig" \
          CFLAGS="-I$(brew --prefix tcl-tk)/include" \
          PYTHON_CONFIGURE_OPTS="--with-tcltk-includes='-I$(brew --prefix tcl-tk)/include' --with-tcltk-libs='-L$(brew --prefix tcl-tk)/lib -ltcl8.6 -ltk8.6'" \
          pyenv install ${{matrix.python-version}}
        pyenv global ${{matrix.python-version}}
    - name: Run the python script without fallback
      shell: bash {0}
      run: |
        EXIT_XVFB=9
        EXIT_FALLBACK=9
        echo "Running normally"
        python -m write_curr_defaults
        EXIT_NORMAL=$?
        if [ "$EXIT_NORMAL" -ne "0" ] ; then
          echo "Trying to start Xvfb"
          type Xvfb
          Xvfb :0 -screen 0 1024x768x16 &
          EXITSTATUS_XVFB=$?
          if [ "$EXITSTATUS_XVFB" -ne "0" ] ; then
            echo "Couldn't run Xvfb"
            EXIT_XVFB="$EXITSTATUS_XVFB"
          else
            sleep 2
            ps aux | grep Xvfb
            echo "Running under Xvfb"
            DISPLAY=:0.0 python -m write_curr_defaults
            EXIT_XVFB=$?
          fi
          if [ "$EXIT_XVFB" -ne "0" ] ; then
            echo "Running fallback"
            TK_DEFAULTS_FALLBACK=1 python -m write_curr_defaults
            EXIT_FALLBACK=$?
          fi
        fi
        if [ "$EXIT_NORMAL" -eq "0" ] || [ "$EXIT_XVFB" -eq "0" ] || [ "$EXIT_FALLBACK" -eq "0" ] ; then
          exit 0
        else
          exit 1
        fi
    - name: Upload artifact for the defaults
      uses: actions/upload-artifact@v4
      with:
        name: "tkinter_defaults__${{ matrix.os }}_${{ matrix.python-version }}"
        path: "tkinter_defaults_curr.json"
    - name: Commit build
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11' }}
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Upload defaults
        commit_author: "github-actions[bot] <actions@github.com>"
        file_pattern: "tkinter_defaults/*.json"
    # TODO: commit + push files for non-UNIX - can't use stefanzweifel's git-auto-commit-action as it is UNIX-only
    # Also, it doesn't properly handle matrix runs
